services:
  fillsensor-server:
    build: "https://github.com/DocDriven/sim-images.git#master:fillsensor-server/open62541/latest"
    ports:
      - "4840:4840"
    environment:
      - TZ=Europe/Berlin
    networks:
      - fillsensor-net
  fillsensor-process-sim:
    build: "https://github.com/DocDriven/sim-images.git#master:fillsensor-process-sim/open62541/latest"
    networks:
      - fillsensor-net
    depends_on:
      - fillsensor-server
networks:
  fillsensor-net:
    external: false
    name: fillsensor-net
