services:
  headunit-client:
    build: "https://github.com/DocDriven/sim-images.git#master:headunit-client/asyncua/latest"
    environment:
      - TZ=Europe/Berlin
      - SERVER_URI=opc.tcp://192.168.10.11:4840
      - INTERVAL=2
    network_mode: bridge
    ports:
      - "8050:8050"
