services:
  plc-logic-client:
    build:
      context: https://github.com/DocDriven/sim-images.git#:plc-logic-client/open62541/latest
    environment:
      - TZ=Europe/Berlin
      - SENSOR_URI=opc.tcp://192.168.10.11:4840
      - ACTUATOR_URI=opc.tcp://192.168.10.12:4840
    volumes:
      - /tmp/docker/database:/database
    network_mode: bridge
  plc-server:
    build:
      context: https://github.com/DocDriven/sim-images.git
      dockerfile: plc-server/open62541/latest/Dockerfile
    ports:
      - "4840:4840"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /tmp/docker/database:/database
